language: generic
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker build --compress --tag apemost/dotfiles:latest .

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push apemost/dotfiles:latest
  on:
    branch: master

notifications:
  email: false
