printWidth: 80
tabWidth: 2
semi: true
singleQuote: false
jsxSingleQuote: false
trailingComma: "all"
bracketSpacing: true
arrowParens: "always"
endOfLine: "lf"
overrides:
  - files:
      - "**/*.{js,jsx,ts,tsx,mjs,mts}"
    options:
      singleQuote: true
