printWidth: 80
tabWidth: 2
semi: true
singleQuote: false
jsxSingleQuote: false
bracketSpacing: true
arrowParens: "always"
endOfLine: "lf"
overrides:
  - files:
      - "**/*.js"
      - "**/*.ts"
    options:
      singleQuote: true
