name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  build:
    name: Build docker image
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --compress --tag apemost/dotfiles:latest .
